export const DEFAULT_ASSIGN = 'DEFAULT_ASSIGN'
export const INIT = "INIT";
export const GET_SUMMONER_REQUEST = "GET_SUMMONER_REQUEST";
export const GET_SUMMONER_SUCCESS = "GET_SUMMONER_SUCCESS";
export const FILTERED_GAMES = 'FILTERED_GAMES'
export const SEARCH_SUMMONER_REQUEST = 'SEARCH_SUMMONER_REQUEST'
export const SEARCH_SUMMONER_SUCCESS = 'SEARCH_SUMMONER_SUCCESS'
