export const GET_SUMMONER_INFO = "GET_SUMMONER_INFO";
export const GET_SUMMONER_MOST_INFO = "GET_SUMMONER_MOST_INFO";
export const GET_SUMONNER_MATCH_LIST = "GET_SUMONNER_MATCH_LIST";
export const GET_SUMMONER_MATCH = "GET_SUMMONER_MATCH"; // 이번엔 제외?
export const GET_ITEM_INFO = "GET_ITEM_INFO";
